Lect9
twas0805/Reposit pull request #10
Opened 2023-11-08 12:13 UTC by twas0805

2023-11-11 09:12 UTC, lamer0k requested changes
прау вопросов.

2023-11-11 09:12 UTC, lamer0k commented on Lection9.adoc
> +*L: Liskov Substitution Principle (Принцип подстановки Барбары Лисков).* Необходимо, чтобы классы-наследники могли бы использоваться вместо родительских классов, от которых они образованы, не нарушая
Описать что такое принцип Liskov -  примеры и почему это хороший принцип.

2023-11-11 09:12 UTC, lamer0k commented on Lection9.adoc
> +== Ёлочка и шахматный режим
Описание, что такое рижмы елочки и шахматки

2023-11-11 09:12 UTC, lamer0k commented on Lection9.adoc
> +#include "imode.h"
for

2023-11-11 09:12 UTC, lamer0k commented on Lection9.adoc
> +  int i = 0;
зачем i атрибут класса?

2023-11-11 09:12 UTC, lamer0k commented on Lection9.adoc
> +  /*ChessMode()
закоменченный код удалить

2023-11-11 09:12 UTC, lamer0k commented on Lection9.adoc
> +    } else if(flag)
зачем else if?

2023-11-17 16:55 UTC, twas0805 commented on Lection9.adoc
> +*L: Liskov Substitution Principle (Принцип подстановки Барбары Лисков).* Необходимо, чтобы классы-наследники могли бы использоваться вместо родительских классов, от которых они образованы, не нарушая
Дописал

2023-11-17 16:55 UTC, twas0805 commented on Lection9.adoc
> +== Ёлочка и шахматный режим
Дописал

2023-11-17 16:55 UTC, twas0805 commented on Lection9.adoc
> +#include "imode.h"
Убрал

2023-11-17 16:55 UTC, twas0805 commented on Lection9.adoc
> +  int i = 0;
Исправил

2023-11-17 16:55 UTC, twas0805 commented on Lection9.adoc
> +  /*ChessMode()
Убрал

2023-11-17 16:56 UTC, twas0805 commented on Lection9.adoc
> +    } else if(flag)
Убрал

2023-11-18 09:12 UTC, lamer0k approved these changes

2023-11-18 12:14 UTC, merged