Lection10
twas0805/Reposit pull request #11
Opened 2023-11-17 18:20 UTC by twas0805

2023-11-18 09:00 UTC, lamer0k commented
Артур, слей проапрувленные лабы. 11:20 PM, 17 ноября 2023 г., twas0805 ***@***.***>:



You can view, comment on, or merge this pull request online at:
  https://github.com/twas0805/Reposit/pull/11

Commit Summary

  49a912b  Lection10


File Changes  (4 files)

  
    A
    Img/UML-leds.jpg
    (0)
  
  
    A
    Lection10.adoc
    (344)
  
  
    A
    Titul_Lection10.adoc
    (26)
  
  
    A
    Video/Perekl_leds.mp4
    (0)
  


Patch Links:

  https://github.com/twas0805/Reposit/pull/11.patch
  https://github.com/twas0805/Reposit/pull/11.diff


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

-- Отправлено из мобильного приложения Яндекс Почты

2023-11-18 09:09 UTC, lamer0k requested changes

2023-11-18 09:09 UTC, lamer0k commented on Lection10.adoc
> +image::img/UML-leds.jpg[]
Картинка не видна

2023-11-18 09:09 UTC, lamer0k commented on Lection10.adoc
> +  *reinterpret_cast<uint32_t*>(0x40020814) = 0;
Никаких непонятных адресов быть не должно. Это уже уровень приложения, про адреса никто знать не должен.

2023-11-18 09:09 UTC, lamer0k commented on Lection10.adoc
> +  *reinterpret_cast<uint32_t*>(0x40020814) = 0;
Тоже переделать, чтобы адресов не было.

2023-11-18 09:09 UTC, lamer0k commented on Lection10.adoc
> +    *reinterpret_cast<uint32_t*>(0x40020014) = 0;
Тоже самое

2023-11-18 09:09 UTC, lamer0k commented on Lection10.adoc
> +  i++;
Можно тут вызвать currentMode - >Clear

2023-11-18 09:09 UTC, lamer0k commented on Lection10.adoc
> +  IMode* currentMode = modifications[0];
Имя переменной типа указатель должно быть с p pCurrentMode

2023-11-18 09:09 UTC, lamer0k commented on Lection10.adoc
> +  if(GPIOC::IDR::IDR13::Get() == 0)
Жёстко привязался к 13 спину, а если кнопка будет на GPIOA. 5, например?

2023-11-18 12:12 UTC, twas0805 commented on Lection10.adoc
> +  i++;
Исправил

2023-11-18 12:12 UTC, twas0805 commented on Lection10.adoc
> +image::img/UML-leds.jpg[]
Исправил

2023-11-18 12:12 UTC, twas0805 commented on Lection10.adoc
> +  *reinterpret_cast<uint32_t*>(0x40020814) = 0;
Исправил

2023-11-18 12:12 UTC, twas0805 commented on Lection10.adoc
> +  *reinterpret_cast<uint32_t*>(0x40020814) = 0;
Исправил

2023-11-18 12:12 UTC, twas0805 commented on Lection10.adoc
> +    *reinterpret_cast<uint32_t*>(0x40020014) = 0;
Исправил

2023-11-18 12:12 UTC, twas0805 commented on Lection10.adoc
> +  IMode* currentMode = modifications[0];
Исправил

2023-11-18 12:12 UTC, twas0805 commented on Lection10.adoc
> +  if(GPIOC::IDR::IDR13::Get() == 0)
Исправил

2023-12-02 10:27 UTC, lamer0k approved these changes

2023-12-02 10:31 UTC, merged