File Lection11
twas0805/Reposit pull request #22
Opened 2023-11-25 08:35 UTC by twas0805

2023-12-02 10:29 UTC, lamer0k requested changes

2023-12-02 10:29 UTC, lamer0k commented on Lection11/allmode.h
> +#ifndef ALLMODE
Не понял, что в PR, только одни заголовончые файлы? Зачем? 
А где отчет?

2023-12-02 10:29 UTC, lamer0k commented on Lection11/main.cpp
> +AllMode<pin1, pin2, pin3, pin4> all; //�������� ������� ������ ����� "���"
кодировка нечитаемая

2023-12-23 18:03 UTC, twas0805 commented on Lection11/allmode.h
> +#ifndef ALLMODE
Исправил

2023-12-23 18:03 UTC, twas0805 commented on Lection11/main.cpp
> +AllMode<pin1, pin2, pin3, pin4> all; //�������� ������� ������ ����� "���"
Исправил

2024-05-04 14:27 UTC, merged