Lection6
twas0805/Reposit pull request #7
Opened 2023-10-19 16:32 UTC by twas0805

2023-10-20 18:52 UTC, lamer0k commented on Lection6.adoc
> +* *Оперативные регистры.* Любая функция может использовать эти регистры так, как ей необходимо. Если после того, как вызвалась новая функция, предыдущей функции нужны значения, хранящиеся в этих реги
то их надо самим сохранять на стеке. А не автоматом, как например, для вспомогательных регисров.

2023-10-20 18:53 UTC, lamer0k commented on Lection6.adoc
> +Регистры специального назначения обозначены 32-битным шестастнадцатеричным числом, у них есть поля с ячейками, в свою очередь каждое поле имеет свою длину. Если поле имеет длину 2 бита, то существует
почему именно 16-ричным,  - просто регистры 32 битные.

2023-10-20 18:54 UTC, lamer0k commented on Lection6.adoc
> +    //Подача на порт С.5 регистра ODR единицы, с использованием алгебры логики
порт и регистр это разные вещи. Порт управляется с помощью регистра. Ты подаешь не на порт регистра, потому что у регистра нет порт, а просто на порт С.5 с помощью регистра ODR, путем установки в его 5 бит единицы.

2023-10-20 18:55 UTC, lamer0k commented on Lection6.adoc
> +  //Подача на порт C.8 регистрыoutput data register (ODR) единицы, т.е. питания, с использованием обертки
у регистра нет порта.

2023-10-20 18:56 UTC, lamer0k commented on Lection6.adoc
> +     //Отключение на порт С.5 регистра ODR единицы, с использованием алгебры логики
Подача едины на порт C.5  путем сброса бита номер 5 регистра ODR

2023-10-20 18:57 UTC, lamer0k commented on Lection6.adoc
> +В результате диод, который связан с портом C.8 будет светиться, а диод, связанный с портом C.5 будет моргать.
светодиод

2023-10-20 18:58 UTC, lamer0k commented on Lection6.adoc
> +Регистры специального назначения обозначены 32-битным шестастнадцатеричным числом, у них есть поля с ячейками, в свою очередь каждое поле имеет свою длину. Если поле имеет длину 2 бита, то существует
Самое главное то и не написал. что регистр специального назначения. это ячейка памяти у которой есть адрес, поэтому обращаться к нему можно как к обычной ячейке памяти, например, через указатель.

2023-10-20 18:58 UTC, lamer0k commented on Lection6.adoc
> +В данной работе было разобрано, что такое регистры, какие бывают типы регистров, как получить доступ к регистрам и  как с ними работать при помощи обертки и алгебры логики.
Вот как получить доступ к регистрам тема не раскрыта :)

2023-10-20 19:00 UTC, lamer0k commented on Lection6.adoc
> +В данной работе было разобрано, что такое регистры, какие бывают типы регистров, как получить доступ к регистрам и  как с ними работать при помощи обертки и алгебры логики.
А гдн вставленное видео?

2023-10-20 19:02 UTC, lamer0k requested changes
Пару замечаний надо поменять

2023-10-20 19:02 UTC, lamer0k commented on Lection6.adoc
> +video::Work with R.mov[]
Че то свалка какя-то в проекте, видео должны быть в папке Video, картинки в папке Img, а в ветке только отчеты с именами Otche0...7

2023-10-22 09:05 UTC, twas0805 commented on Lection6.adoc
> +* *Оперативные регистры.* Любая функция может использовать эти регистры так, как ей необходимо. Если после того, как вызвалась новая функция, предыдущей функции нужны значения, хранящиеся в этих реги
Исправил

2023-10-22 09:05 UTC, twas0805 commented on Lection6.adoc
> +Регистры специального назначения обозначены 32-битным шестастнадцатеричным числом, у них есть поля с ячейками, в свою очередь каждое поле имеет свою длину. Если поле имеет длину 2 бита, то существует
Исправил

2023-10-22 09:06 UTC, twas0805 commented on Lection6.adoc
> +    //Подача на порт С.5 регистра ODR единицы, с использованием алгебры логики
Исправил

2023-10-22 09:06 UTC, twas0805 commented on Lection6.adoc
> +  //Подача на порт C.8 регистрыoutput data register (ODR) единицы, т.е. питания, с использованием обертки
Исправил

2023-10-22 09:06 UTC, twas0805 commented on Lection6.adoc
> +     //Отключение на порт С.5 регистра ODR единицы, с использованием алгебры логики
Исправил

2023-10-22 09:06 UTC, twas0805 commented on Lection6.adoc
> +В результате диод, который связан с портом C.8 будет светиться, а диод, связанный с портом C.5 будет моргать.
Исправил

2023-10-22 09:06 UTC, twas0805 commented on Lection6.adoc
> +В данной работе было разобрано, что такое регистры, какие бывают типы регистров, как получить доступ к регистрам и  как с ними работать при помощи обертки и алгебры логики.
Исправил

2023-10-22 09:22 UTC, twas0805 commented on Lection6.adoc
> +video::Work with R.mov[]
Исправил

2023-10-28 07:45 UTC, lamer0k approved these changes

2023-10-31 15:59 UTC, merged