Lect7
twas0805/Reposit pull request #8
Opened 2023-10-22 18:17 UTC by twas0805

2023-10-28 07:48 UTC, lamer0k requested changes

2023-10-28 07:48 UTC, lamer0k commented on Lection7.adoc
> +Результатом унарного оператора плюса (+) является значение его операнда. Так же если операнд имеет тип char и к нему применить унарный плюс, то операнд приведётся к типу int и будет иметь значение, с
Это называется IntegerPromotion, т.е. оператор расширяет тип до типа Int. Такое же поведение кстати и для унарных операторов - и ~ вообще, вот для такого случая:
char a, b; char c = a+b;   
тоже будет выполнятся Integer promotion для результата a+b, но потом он обрежется до типа char.

2023-10-28 07:48 UTC, lamer0k commented on Lection7.adoc
> +  printf("%d", +ch);
лучше использовать std::cout <<

2023-10-28 07:48 UTC, lamer0k commented on Lection7.adoc
> +Оператор запятая (,) позволяет вычислять несколько выражений везде, где разрешено одно выражение. Оператор запятая вычисляет левый операнд, затем правый операнд, а затем возвращает результат правого
еще такой пример можно использовать:
char a = (std::cout << "Определяю переменную" << std::endl , 4);
Здесь вначале выведется сообщение, а затем a присвоится 4:
но оператор запятая использовать не надо - это зло. Усложняет понимание программы.

2023-10-28 07:48 UTC, lamer0k commented on Lection7.adoc
> +Используя данную формулу, нужно подобрать только соответствующие коэффициенты. Можно взять следующие коэффициенты: PLLN = 128, PLLM = 32, PLLP = 2.
Там еще есть уcловия для FCO, их почему не проверил?

2023-10-28 07:48 UTC, lamer0k commented on Lection7.adoc
> +  *reinterpret_cast<std::uint32_t*>(0x40023804) |= (1U << 5U);
В файле, где регистры определены...

struct PLLCFGR : public RegisterBase<0x40023804, 32, ReadWriteMode> { using PLLQ0 = RCC_PLLCFGR_PLLQ_Values<RCC::PLLCFGR, 24, 4, ReadWriteMode, RCCPLLCFGRBase> ; using PLLSRC = RCC_PLLCFGR_PLLSRC_Values<RCC::PLLCFGR, 22, 1, ReadWriteMode, RCCPLLCFGRBase> ; using PLLP0 = RCC_PLLCFGR_PLLP_Values<RCC::PLLCFGR, 16, 2, ReadWriteMode, RCCPLLCFGRBase> ; using PLLN0 = RCC_PLLCFGR_PLLN_Values<RCC::PLLCFGR, 6, 9, ReadWriteMode, RCCPLLCFGRBase> ; using FieldValues = RCC_PLLCFGR_PLLM_Values<RCC::PLLCFGR, 0, 5, NoAccess, NoAccess> ; } ;
надо поменять на
struct PLLCFGR : public RegisterBase<0x40023804, 32, ReadWriteMode> { using PLLQ0 = RCC_PLLCFGR_PLLQ_Values<RCC::PLLCFGR, 24, 4, ReadWriteMode, RCCPLLCFGRBase> ; using PLLSRC = RCC_PLLCFGR_PLLSRC_Values<RCC::PLLCFGR, 22, 1, ReadWriteMode, RCCPLLCFGRBase> ; using PLLP0 = RCC_PLLCFGR_PLLP_Values<RCC::PLLCFGR, 16, 2, ReadWriteMode, RCCPLLCFGRBase> ; using PLLN0 = RCC_PLLCFGR_PLLN_Values<RCC::PLLCFGR, 6, 9, ReadWriteMode, RCCPLLCFGRBase> ; using PLLM0 = RCC_PLLCFGR_PLLM_Values<RCC::PLLCFGR, 0, 5, ReadWriteMode, RCCPLLCFGRBase> ; using FieldValues = RCC_PLLCFGR_PLLM_Values<RCC::PLLCFGR, 0, 0, NoAccess, NoAccess> ; } ;

2023-10-28 07:48 UTC, lamer0k commented on Lection7.adoc
> +  *reinterpret_cast<std::uint32_t*>(0x40023804) |= (1U << 13U);
RCC::PLLCFGR::write(1U << 13U);

2023-11-05 09:32 UTC, twas0805 commented on Lection7.adoc
> +Результатом унарного оператора плюса (+) является значение его операнда. Так же если операнд имеет тип char и к нему применить унарный плюс, то операнд приведётся к типу int и будет иметь значение, с
Исправил

2023-11-05 09:32 UTC, twas0805 commented on Lection7.adoc
> +  printf("%d", +ch);
Исправил

2023-11-05 09:32 UTC, twas0805 commented on Lection7.adoc
> +Оператор запятая (,) позволяет вычислять несколько выражений везде, где разрешено одно выражение. Оператор запятая вычисляет левый операнд, затем правый операнд, а затем возвращает результат правого
Исправил

2023-11-05 09:32 UTC, twas0805 commented on Lection7.adoc
> +Используя данную формулу, нужно подобрать только соответствующие коэффициенты. Можно взять следующие коэффициенты: PLLN = 128, PLLM = 32, PLLP = 2.
Исправил

2023-11-05 09:32 UTC, twas0805 commented on Lection7.adoc
> +  *reinterpret_cast<std::uint32_t*>(0x40023804) |= (1U << 5U);
Исправил

2023-11-11 09:07 UTC, lamer0k approved these changes

2023-11-15 14:54 UTC, merged